version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smicrab_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smicrab-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smicrab_backend
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      PROJECT_PATH: ${PROJECT_PATH}
    
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./datasets:/app/datasets
      - ./datasets_csv:/app/datasets_csv
      - ./logs:/app/logs
      - ./r_scripts:/app/r_scripts
      - ./.env:/app/.env
      - ./tmp/analysis:/tmp/analysis
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - smicrab-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      start_period: 1200s
      retries: 5

  analysis:
      image: smicrab-analysis:latest
      profiles:
        - "donotstart"
      volumes:
        - ./tmp/analysis:/tmp/analysis
        - ./r_scripts:/app/r_scripts:ro
        - ./datasets:/app/datasets:ro
        - ./datasets_csv:/app/datasets_csv:ro
      networks:
        - smicrab-net
    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smicrab_pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - smicrab-net
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  smicrab-net:
    driver: bridge
    name: smicrab-net
